travelapp/urls.py
from django.urls import path
from . import views
app_name='travelapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('places/<int:places_id>/',views.detail,name='detail'),
    path('add/',views.add,name='add'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),


]

travelproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("travelapp.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

travelapp/models.py
from django.db import models


class Places(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    img = models.ImageField(upload_to='gallary')

    def __str__(self):
        return self.name

travelapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Places
from .form import PlaceForm


def index(request):
    places = Places.objects.all()

    content = {
        'place_list': places
    }
    return render(request, 'index.html', content)


def detail(request, places_id):
    places = Places.objects.get(id=places_id)
    return render(request, "detail.html", {'places': places})


def add(request):
    if request.method == "POST":
        name = request.POST.get('name', )
        desc = request.POST.get('desc', )
        img = request.FILES['img']
        places = Places(name=name, desc=desc, img=img)
        places.save()
    return render(request, 'add.html')


def update(request, id):
    places = Places.objects.get(id=id)
    form = PlaceForm(request.POST or None, request.FILES, instance=places)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'places': places})


def delete(request, id):
    if request.method == 'POST':
        places = Places.objects.get(id=id)
        places.delete()
        return redirect('/')
    return render(request, 'delete.html')

templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Add place name"><br>
    <input type="text" name="desc" placeholder="Add description"><br>
    <input type="file" name="img"><br>
    <input type="submit">
</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css'  %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      India's Tourist Places</a>
    <form class="form-inline my-2 my-lg-0">
                    <a class="btn btn-info" href="add/">Add</a><br>
    </form>
</nav>
{%  block body  %}
{% endblock %}
</body>
</html>

templates/delete.html
<form method="POST">
    {%  csrf_token %}
    Are you want to delete this movie?<br>
    <input type="submit">

</form>

templates/detail.html
{% extends 'base.html' %}
{% block body %}
    <div class="container">
     <div class="row">
       <div class="col-md-6">
           <img  src="{{ places.img.url }}" width="300" height="300">
            </div>
         <div class="col-md-6">

       <h2>{{ places.name }}</h2><br>
       <h6>{{ places.desc }}</h6><br>
             <a class="btn btn-info" href="{% url 'travelapp:update' places.id %}" >update</a>
       <a class="btn btn-danger" href="{% url 'travelapp:delete' places.id %}">delete</a>
    
          </div>
        </div>
     </div>


{% endblock %}

templates/edit.html
<form method="post" enctype="multipart/form-data">
    {%  csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>

templates/index.html
{% extends 'base.html' %}
{% block body  %}


    <div class="container">
         <div class="row">

             {% for i in place_list %}
             <div class="col-md-4"><hr>
                 <div class="card">
                      <img  src="{{ i.img.url }}" class="card-img-top" alt="" height="250px">
                      <div class="card-body">
                            <h5 class="card-title">{{ i.name }}</h5>

                            <a class="btn btn-success" href="{% url 'travelapp:detail' i.id %}" >View Details</a>

                      </div>
                 </div>
             </div>

              {% endfor %}


         </div>
    </div>

{% endblock %}